import prisma from '../src/db.js';
import bcrypt from 'bcrypt'

async function main() {
  console.log('🌱 Starting seed...');

  // Create seed user (replace with your details)
  const hashedPassword = await bcrypt.hash('password123', 10);
  
  const seedUser = await prisma.user.upsert({
    where: { email: 'team@unimunch.com' },
    update: {},
    create: {
      email: 'team@unimunch.com',
      username: 'unimunch_team',
      password: hashedPassword,
      name: 'UniMunch Team',
      school: 'UniSA',
      role: 'UNIVERSITY',
    },
  });

  console.log('Seed user created');

  await prisma.recipe.deleteMany({
    where: { userId: seedUser.id }
  });

  console.log('cleared exisiting seed')

  // 25 Recipes
  const recipes = [
    // QUICK MEALS
    {
      title: 'Lazy Garlic Spaghetti',
      ingredients: '200g spaghetti ($1.20), 6 garlic cloves ($0.30), 3 tbsp olive oil ($0.50), chili flakes ($0.10), 30g parmesan ($1.50)',
      instructions: '1. Boil spaghetti in salted water for 8-10 min. 2. While pasta cooks, thinly slice garlic. 3. Heat olive oil in pan, add garlic and chili, cook until fragrant (30 sec). 4. Drain pasta, toss with garlic oil. 5. Top with grated parmesan.',
      timeTaken: 'Prep: 5min, Cook: 10min',
      cost: 3.60,
      tags: ['quick', 'cheap', 'vegetarian', 'pasta'],
      description: 'when ur broke but need something that slaps',
      imageUrl: 'https://plus.unsplash.com/premium_photo-1661445014453-784cd6c59ac8?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: '5-Minute Egg Fried Rice',
      ingredients: '2 cups day-old rice ($0.80), 2 eggs ($0.80), 1 cup frozen mixed veg ($0.60), 2 tbsp soy sauce ($0.20), 1 tsp sesame oil ($0.10), 2 spring onions ($0.40)',
      instructions: '1. Heat wok or large pan on high. 2. Scramble eggs, set aside. 3. Add rice, break up clumps, fry for 2 min. 4. Add frozen veg, cook 1 min. 5. Add eggs back, drizzle soy sauce and sesame oil. 6. Toss everything, top with chopped spring onions.',
      timeTaken: 'Prep: 2min, Cook: 5min',
      cost: 2.90,
      tags: ['quick', 'cheap', 'asian', 'egg'],
      description: 'leftover rice救星, tastes better than it should',
      imageUrl: 'https://images.unsplash.com/photo-1609570324378-ec0c4c9b6ba8?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Instant Ramen Upgrade',
      ingredients: '1 pack instant noodles ($1.00), 1 egg ($0.40), handful spinach ($0.50), 2 slices cheese ($0.60), spring onion ($0.20), sesame oil ($0.10)',
      instructions: '1. Boil water, cook noodles for 2 min. 2. Add spinach in last 30 seconds. 3. Crack egg directly into pot, stir gently. 4. Add flavor packet and cheese slices, stir until melted. 5. Drizzle sesame oil, top with spring onions.',
      timeTaken: 'Prep: 2min, Cook: 3min',
      cost: 2.80,
      tags: ['quick', 'cheap', 'asian', 'noodles'],
      description: 'fancy ramen for when u cant be bothered',
      imageUrl: 'https://images.unsplash.com/photo-1759923593745-6302b220d719?q=80&w=2230&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Microwave Mug Omelette',
      ingredients: '2 eggs ($0.80), 2 tbsp milk ($0.10), handful grated cheese ($0.50), salt & pepper ($0.05), optional: diced ham/tomato ($0.50)',
      instructions: '1. Crack eggs into microwave-safe mug. 2. Add milk, cheese, salt, pepper, and any extras. 3. Whisk with fork. 4. Microwave for 1 min, stir. 5. Microwave another 30-60 sec until set.',
      timeTaken: 'Prep: 2min, Cook: 2min',
      cost: 1.95,
      tags: ['quick', 'cheap', 'breakfast', 'egg', 'microwave'],
      description: 'breakfast speedrun any%',
      imageUrl: 'https://images.pexels.com/photos/1887932/pexels-photo-1887932.jpeg?auto=compress&cs=tinysrgb&w=400',
      userId: seedUser.id,
    },
    {
      title: 'Lazy Peanut Noodles',
      ingredients: '200g dried noodles ($1.00), 3 tbsp peanut butter ($0.60), 2 tbsp soy sauce ($0.20), 1 tbsp honey ($0.30), 1 tsp rice vinegar ($0.10), cucumber ($0.80), spring onion ($0.20)',
      instructions: '1. Cook noodles according to packet. 2. Mix peanut butter, soy sauce, honey, vinegar with 2 tbsp hot pasta water. 3. Drain noodles, toss with sauce. 4. Top with sliced cucumber and spring onions.',
      timeTaken: 'Prep: 5min, Cook: 8min',
      cost: 3.20,
      tags: ['quick', 'vegetarian', 'asian', 'noodles', 'peanut'],
      description: 'tastes expensive but costs nothing',
      imageUrl: 'https://images.unsplash.com/photo-1610554675919-858d84c76d40?q=80&w=2231&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Cheese Quesadilla Deluxe',
      ingredients: '2 flour tortillas ($0.80), 1 cup grated cheese ($1.20), 1/4 onion ($0.20), 1/2 capsicum ($0.60), optional: sour cream ($0.50)',
      instructions: '1. Dice onion and capsicum finely. 2. Heat pan, place one tortilla. 3. Sprinkle half the cheese, add veg, top with remaining cheese and second tortilla. 4. Cook 2 min each side until golden. 5. Cut into quarters, serve with sour cream.',
      timeTaken: 'Prep: 3min, Cook: 5min',
      cost: 3.30,
      tags: ['quick', 'cheap', 'vegetarian', 'mexican'],
      description: 'grilled cheese but make it fancy',
      imageUrl: 'https://images.unsplash.com/photo-1647545401800-bd8f77e670ed?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Tuna Pasta Bake (Single Serve)',
      ingredients: '100g pasta ($0.60), 1 can tuna ($2.00), 1/2 cup frozen peas ($0.30), 2 tbsp cream cheese ($0.40), 1/4 cup grated cheese ($0.40)',
      instructions: '1. Cook pasta, drain but keep 1/4 cup pasta water. 2. Mix pasta, tuna, peas, cream cheese, and pasta water in microwave-safe bowl. 3. Top with grated cheese. 4. Microwave 2 min or until cheese melts.',
      timeTaken: 'Prep: 3min, Cook: 10min',
      cost: 3.70,
      tags: ['quick', 'pasta', 'tuna', 'microwave'],
      description: 'protein hit without actually cooking',
      imageUrl: 'https://plus.unsplash.com/premium_photo-1705947846996-2887733378a3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Veggie Fried Noodles',
      ingredients: '200g fresh hokkien noodles ($2.00), 1 cup mixed frozen veg ($0.60), 2 eggs ($0.80), 2 tbsp oyster sauce ($0.30), 1 tbsp soy sauce ($0.10), garlic ($0.20)',
      instructions: '1. Rinse noodles in hot water to separate. 2. Heat wok, scramble eggs, set aside. 3. Stir-fry garlic and frozen veg for 2 min. 4. Add noodles, oyster sauce, soy sauce. 5. Toss everything together with eggs.',
      timeTaken: 'Prep: 3min, Cook: 6min',
      cost: 4.00,
      tags: ['quick', 'asian', 'noodles', 'vegetarian'],
      description: 'takeaway vibes at home',
      imageUrl: 'https://plus.unsplash.com/premium_photo-1695044277387-4ee7eaf417ff?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Avocado Toast Actually Worth It',
      ingredients: '2 slices bread ($0.40), 1 avocado ($2.50), 1 egg ($0.40), chili flakes ($0.05), lemon juice ($0.10), salt & pepper ($0.05)',
      instructions: '1. Toast bread. 2. Mash avocado with lemon juice, salt, pepper. 3. Fry egg to your liking. 4. Spread avo on toast, top with egg and chili flakes.',
      timeTaken: 'Prep: 2min, Cook: 5min',
      cost: 3.50,
      tags: ['quick', 'breakfast', 'vegetarian', 'avocado'],
      description: 'millennial breakfast but make it cheap',
      imageUrl: 'https://images.unsplash.com/photo-1633204339916-6ddd69d426e9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Korean-ish Beef Rice Bowl',
      ingredients: '200g beef mince ($3.00), 2 cups rice ($0.80), 2 tbsp soy sauce ($0.20), 1 tbsp brown sugar ($0.10), 1 tsp sesame oil ($0.10), garlic ($0.20), fried egg ($0.40), spring onion ($0.20)',
      instructions: '1. Cook rice. 2. Brown mince with garlic. 3. Add soy sauce, sugar, sesame oil, cook until caramelized. 4. Serve over rice with fried egg on top. 5. Garnish with spring onions.',
      timeTaken: 'Prep: 5min, Cook: 12min',
      cost: 5.00,
      tags: ['quick', 'asian', 'beef', 'rice', 'korean'],
      description: 'bulgogi at home minus the effort',
      imageUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Tomato Egg Stir Fry',
      ingredients: '3 eggs ($1.20), 2 tomatoes ($1.50), 1 tbsp ketchup ($0.20), 1 tsp sugar ($0.05), spring onion ($0.20), rice to serve ($0.80)',
      instructions: '1. Cut tomatoes into wedges. 2. Scramble eggs until just set, remove. 3. Stir-fry tomatoes until soft. 4. Add ketchup and sugar. 5. Add eggs back, toss together. 6. Serve over rice with spring onions.',
      timeTaken: 'Prep: 5min, Cook: 8min',
      cost: 3.95,
      tags: ['quick', 'cheap', 'asian', 'egg', 'vegetarian'],
      description: 'chinese comfort food that hits different',
      imageUrl: 'https://images.unsplash.com/photo-1582492710145-d723e0a219f8?q=80&w=1649&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Spicy Peanut Butter Toast',
      ingredients: '2 slices bread ($0.40), 2 tbsp peanut butter ($0.40), honey ($0.20), chili flakes ($0.05), banana ($0.80)',
      instructions: '1. Toast bread. 2. Spread peanut butter generously. 3. Drizzle honey, sprinkle chili flakes. 4. Top with sliced banana if using.',
      timeTaken: 'Prep: 2min, Cook: 2min',
      cost: 1.85,
      tags: ['quick', 'cheap', 'breakfast', 'vegetarian', 'spicy'],
      description: 'sweet spicy chaos that works',
      imageUrl: 'https://images.unsplash.com/photo-1664350454685-a3298c47fb58?q=80&w=1626&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Microwave Mac & Cheese',
      ingredients: '1 cup macaroni ($0.60), 1 cup water ($0), 1/4 cup milk ($0.20), 3/4 cup grated cheese ($0.90), salt & pepper ($0.05)',
      instructions: '1. Put pasta and water in large microwave-safe bowl. 2. Microwave 3 min, stir, microwave 3 more min. 3. Stir in milk and cheese until melted. 4. Season with salt and pepper.',
      timeTaken: 'Prep: 1min, Cook: 6min',
      cost: 1.75,
      tags: ['quick', 'cheap', 'vegetarian', 'pasta', 'microwave'],
      description: 'no pot no problem',
      imageUrl: 'https://images.unsplash.com/photo-1708184528301-b0dad28dded5?q=80&w=1682&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Kimchi Fried Rice',
      ingredients: '2 cups day-old rice ($0.80), 1 cup kimchi ($1.50), 2 eggs ($0.80), 1 tbsp gochujang ($0.30), sesame oil ($0.10), spring onion ($0.20)',
      instructions: '1. Chop kimchi into small pieces. 2. Heat pan, fry kimchi for 2 min. 3. Add rice and gochujang, mix well. 4. Make space in center, crack eggs, scramble. 5. Mix everything, drizzle sesame oil, top with spring onions.',
      timeTaken: 'Prep: 3min, Cook: 7min',
      cost: 3.70,
      tags: ['quick', 'asian', 'korean', 'spicy', 'rice'],
      description: 'hangover cure that actually works',
      imageUrl: 'https://images.unsplash.com/photo-1600688654899-379ec76aca42?q=80&w=2204&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Lazy Shakshuka',
      ingredients: '1 can crushed tomatoes ($1.20), 2 eggs ($0.80), 1/2 onion ($0.30), garlic ($0.20), 1 tsp cumin ($0.10), bread for dipping ($0.40)',
      instructions: '1. Dice onion, fry with garlic until soft. 2. Add tomatoes and cumin, simmer 5 min. 3. Make two wells, crack eggs into each. 4. Cover and cook until eggs set (5-7 min). 5. Serve with bread for dipping.',
      timeTaken: 'Prep: 5min, Cook: 12min',
      cost: 3.00,
      tags: ['quick', 'vegetarian', 'egg', 'breakfast'],
      description: 'fancy breakfast for broke students',
      imageUrl: 'https://images.unsplash.com/photo-1542895364-1f38d277f031?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
  
    // MEAL PREP
    {
      title: 'Bulk Chicken Fried Rice (4 serves)',
      ingredients: '500g chicken thigh ($6.00), 4 cups rice ($3.20), 2 cups frozen mixed veg ($1.20), 4 eggs ($1.60), 1/4 cup soy sauce ($0.40), sesame oil ($0.20), spring onions ($0.60)',
      instructions: '1. Cook rice, spread on tray to cool. 2. Dice chicken, season with salt. 3. Cook chicken until done, set aside. 4. Scramble eggs, set aside. 5. Fry rice in batches until slightly crispy. 6. Add veg, chicken, eggs, soy sauce, sesame oil. 7. Mix well, divide into 4 containers, top with spring onions.',
      timeTaken: 'Prep: 15min, Cook: 25min',
      cost: 13.20,
      tags: ['meal-prep', 'asian', 'chicken', 'rice', 'freezable'],
      description: 'cook once eat for days',
      imageUrl: 'https://images.unsplash.com/photo-1687020835955-59528e8c91dd?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Budget Butter Chicken (5 serves)',
      ingredients: '600g chicken thigh ($7.20), 2 cans crushed tomatoes ($2.40), 1 cup cream ($2.00), 1 onion ($0.60), 4 garlic cloves ($0.20), ginger ($0.40), 2 tbsp curry powder ($0.60), rice to serve ($4.00)',
      instructions: '1. Dice chicken, marinate in curry powder. 2. Dice onion, mince garlic and ginger. 3. Fry chicken until browned, set aside. 4. Fry onion, garlic, ginger until soft. 5. Add tomatoes, simmer 10 min. 6. Add cream and chicken, simmer 15 min. 7. Divide into containers, serve with rice.',
      timeTaken: 'Prep: 15min, Cook: 35min',
      cost: 17.40,
      tags: ['meal-prep', 'indian', 'chicken', 'curry', 'freezable'],
      description: 'better than takeaway and way cheaper',
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Veggie Stir Fry Batch (4 serves)',
      ingredients: '500g tofu ($3.50), 3 cups mixed veg ($2.40), 1/2 cup cashews ($2.00), 1/4 cup soy sauce ($0.40), 2 tbsp hoisin sauce ($0.50), garlic & ginger ($0.40), rice/noodles to serve ($3.20)',
      instructions: '1. Press tofu, cut into cubes. 2. Fry tofu until golden, set aside. 3. Stir-fry garlic, ginger, veg on high heat. 4. Add soy sauce, hoisin, tofu, cashews. 5. Toss everything, divide into containers. 6. Store rice/noodles separately.',
      timeTaken: 'Prep: 15min, Cook: 20min',
      cost: 12.40,
      tags: ['meal-prep', 'vegetarian', 'asian', 'tofu', 'vegan'],
      description: 'plant based but actually filling',
      imageUrl: 'https://plus.unsplash.com/premium_photo-1770646003620-2d860f453d26?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Spaghetti Bolognese Batch (6 serves)',
      ingredients: '500g beef mince ($6.00), 2 cans crushed tomatoes ($2.40), 1 onion ($0.60), 2 carrots ($0.80), 2 celery stalks ($0.80), garlic ($0.20), 600g spaghetti ($3.60), parmesan ($3.00)',
      instructions: '1. Dice onion, carrot, celery finely. 2. Brown mince, set aside. 3. Fry veg until soft. 4. Add mince back, add tomatoes, simmer 30 min. 5. Divide sauce into containers. 6. Cook pasta fresh when serving, freeze sauce only.',
      timeTaken: 'Prep: 15min, Cook: 40min',
      cost: 17.40,
      tags: ['meal-prep', 'italian', 'beef', 'pasta', 'freezable'],
      description: 'classic that never gets old',
      imageUrl: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Burrito Bowl Prep (4 serves)',
      ingredients: '400g chicken thigh ($4.80), 2 cups rice ($1.60), 1 can black beans ($1.20), 1 cup corn ($0.80), 2 capsicums ($2.40), taco seasoning ($0.80), sour cream & cheese ($3.00)',
      instructions: '1. Cook rice, divide into containers. 2. Season and cook chicken, slice into strips. 3. Drain and rinse beans. 4. Dice capsicum, char in pan. 5. Divide chicken, beans, corn, capsicum into containers. 6. Store sour cream and cheese separately, add when eating.',
      timeTaken: 'Prep: 15min, Cook: 20min',
      cost: 14.60,
      tags: ['meal-prep', 'mexican', 'chicken', 'rice', 'healthy'],
      description: 'chipotle at home for a week',
      imageUrl: 'https://images.unsplash.com/photo-1647545401834-39096eb7e4ad?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
  
    // VEGETARIAN
    {
      title: 'Lentil Daal',
      ingredients: '1 cup red lentils ($1.20), 1 can coconut milk ($2.00), 1 onion ($0.60), 3 garlic cloves ($0.15), ginger ($0.30), 1 tbsp curry powder ($0.30), spinach ($1.00), rice to serve ($0.80)',
      instructions: '1. Rinse lentils. 2. Fry onion, garlic, ginger until soft. 3. Add curry powder, fry 30 sec. 4. Add lentils and 2 cups water, simmer 20 min. 5. Add coconut milk and spinach, cook 5 min. 6. Serve over rice.',
      timeTaken: 'Prep: 10min, Cook: 25min',
      cost: 6.35,
      tags: ['vegetarian', 'indian', 'lentils', 'vegan', 'healthy'],
      description: 'cheap protein that doesnt taste cheap',
      imageUrl: 'https://plus.unsplash.com/premium_photo-1701064865162-db655bfb998f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Veggie Pad Thai',
      ingredients: '200g rice noodles ($1.50), 200g tofu ($1.40), 2 eggs ($0.80), bean sprouts ($1.00), 3 tbsp tamarind paste ($0.60), 2 tbsp peanut butter ($0.40), lime ($0.50), peanuts ($0.80), spring onion ($0.20)',
      instructions: '1. Soak noodles in hot water. 2. Mix tamarind, peanut butter, 2 tbsp water for sauce. 3. Fry tofu, set aside. 4. Scramble eggs, set aside. 5. Stir-fry drained noodles with sauce. 6. Add tofu, eggs, bean sprouts. 7. Top with peanuts, lime, spring onions.',
      timeTaken: 'Prep: 10min, Cook: 10min',
      cost: 7.20,
      tags: ['vegetarian', 'asian', 'thai', 'noodles', 'tofu'],
      description: 'thai food without leaving ur room',
      imageUrl: 'https://images.unsplash.com/photo-1645500498403-970672caf43e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Caprese Pasta',
      ingredients: '200g pasta ($1.20), 200g cherry tomatoes ($2.00), 100g mozzarella ($2.50), fresh basil ($1.50), 2 garlic cloves ($0.10), olive oil ($0.50), balsamic ($0.30)',
      instructions: '1. Cook pasta. 2. Halve tomatoes, tear mozzarella. 3. Heat olive oil, add garlic and tomatoes, cook until soft. 4. Toss pasta with tomatoes, mozzarella, basil. 5. Drizzle balsamic vinegar.',
      timeTaken: 'Prep: 5min, Cook: 12min',
      cost: 8.10,
      tags: ['vegetarian', 'italian', 'pasta', 'fresh'],
      description: 'fancy vibes minimal effort',
      imageUrl: 'https://plus.unsplash.com/premium_photo-1705686155091-339e78cebfea?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Chickpea Curry',
      ingredients: '2 cans chickpeas ($2.40), 1 can crushed tomatoes ($1.20), 1 can coconut milk ($2.00), 1 onion ($0.60), 3 garlic cloves ($0.15), ginger ($0.30), 2 tbsp curry powder ($0.60), spinach ($1.00), rice ($0.80)',
      instructions: '1. Fry onion, garlic, ginger. 2. Add curry powder, fry 30 sec. 3. Add tomatoes, simmer 10 min. 4. Add drained chickpeas and coconut milk, simmer 10 min. 5. Stir in spinach until wilted. 6. Serve over rice.',
      timeTaken: 'Prep: 10min, Cook: 25min',
      cost: 9.05,
      tags: ['vegetarian', 'indian', 'chickpea', 'vegan', 'curry'],
      description: 'vegan and actually tasty',
      imageUrl: 'https://images.unsplash.com/photo-1582576163090-09d3b6f8a969?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },
    {
      title: 'Margherita Flatbread Pizza',
      ingredients: '2 flatbreads ($1.60), 1/2 cup tomato paste ($0.40), 150g mozzarella ($3.00), fresh basil ($1.50), olive oil ($0.30), garlic ($0.10)',
      instructions: '1. Preheat oven to 220°C. 2. Mix tomato paste with crushed garlic and olive oil. 3. Spread on flatbreads. 4. Top with torn mozzarella and basil. 5. Bake 10 min until cheese bubbles.',
      timeTaken: 'Prep: 5min, Cook: 10min',
      cost: 6.90,
      tags: ['vegetarian', 'italian', 'pizza', 'quick'],
      description: 'pizza night on a budget',
      imageUrl: 'https://images.unsplash.com/photo-1764024945383-1a50f23aad92?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      userId: seedUser.id,
    },

    // NEW: 30 Additional Recipes

// ASIAN CUISINE
{
    title: 'Crispy Korean Fried Chicken',
    ingredients: '500g chicken wings ($6.00), 1/2 cup cornstarch ($0.40), 3 tbsp gochujang ($0.60), 2 tbsp honey ($0.40), 2 tbsp soy sauce ($0.20), garlic ($0.20), sesame seeds ($0.20)',
    instructions: '1. Pat chicken dry, coat in cornstarch. 2. Deep fry until crispy (12-15 min). 3. Mix gochujang, honey, soy sauce, minced garlic. 4. Toss fried chicken in sauce. 5. Garnish with sesame seeds.',
    timeTaken: 'Prep: 10min, Cook: 20min',
    cost: 8.00,
    tags: ['korean', 'chicken', 'spicy', 'crispy'],
    description: 'better than any takeaway kfc',
    imageUrl: 'https://images.pexels.com/photos/2313686/pexels-photo-2313686.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Authentic Vietnamese Pho',
    ingredients: '300g beef slices ($4.50), 200g rice noodles ($1.50), 4 cups beef stock ($2.00), star anise ($0.30), ginger ($0.30), fish sauce ($0.20), bean sprouts ($0.80), basil & lime ($0.60)',
    instructions: '1. Simmer stock with star anise, ginger for 20 min. 2. Cook rice noodles separately. 3. Blanch beef slices in hot stock. 4. Assemble: noodles, beef, pour hot stock. 5. Top with bean sprouts, basil, lime, chili.',
    timeTaken: 'Prep: 15min, Cook: 25min',
    cost: 10.20,
    tags: ['vietnamese', 'soup', 'beef', 'noodles'],
    description: 'hangover cure that actually works',
    imageUrl: 'https://images.unsplash.com/photo-1590420882553-4f9150b71f92?q=80&w=2065&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Japanese Chicken Katsu Curry',
    ingredients: '2 chicken breasts ($5.00), 1 cup panko breadcrumbs ($1.00), 1 egg ($0.40), flour ($0.20), 2 tbsp curry powder ($0.60), 1 onion ($0.60), 2 carrots ($0.80), rice ($0.80)',
    instructions: '1. Pound chicken thin, coat in flour, egg, panko. 2. Fry until golden. 3. Make curry: fry onion, carrot, add curry powder and water, simmer 15 min. 4. Slice katsu, serve over rice with curry.',
    timeTaken: 'Prep: 15min, Cook: 25min',
    cost: 9.40,
    tags: ['japanese', 'chicken', 'curry', 'rice'],
    description: 'japanese comfort food done right',
    imageUrl: 'https://images.unsplash.com/photo-1679279727895-bd5c9fb9c1a0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Thai Basil Beef Stir Fry',
    ingredients: '300g beef strips ($4.50), 2 cups Thai basil ($1.50), 3 garlic cloves ($0.15), 2 Thai chilies ($0.20), 2 tbsp fish sauce ($0.20), 1 tbsp oyster sauce ($0.15), jasmine rice ($0.80)',
    instructions: '1. Cook rice. 2. Heat wok to smoking hot. 3. Stir-fry beef until browned, remove. 4. Fry garlic and chilies. 5. Add beef back, add sauces. 6. Toss in basil until wilted. 7. Serve over rice.',
    timeTaken: 'Prep: 10min, Cook: 8min',
    cost: 7.50,
    tags: ['thai', 'beef', 'spicy', 'quick', 'asian'],
    description: 'spicy af but so good',
    imageUrl: 'https://images.pexels.com/photos/725997/pexels-photo-725997.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Chinese Honey Sesame Chicken',
    ingredients: '400g chicken thigh ($4.80), 1/4 cup honey ($0.80), 3 tbsp soy sauce ($0.30), 2 tbsp rice vinegar ($0.20), sesame oil ($0.10), 2 tbsp sesame seeds ($0.40), cornstarch ($0.20), rice ($0.80)',
    instructions: '1. Cut chicken into chunks, coat in cornstarch. 2. Fry until crispy. 3. Mix honey, soy sauce, vinegar, sesame oil in pan. 4. Toss chicken in sauce until glazed. 5. Sprinkle sesame seeds. 6. Serve over rice.',
    timeTaken: 'Prep: 10min, Cook: 15min',
    cost: 7.60,
    tags: ['chinese', 'chicken', 'sweet', 'asian'],
    description: 'sweet sticky perfection',
    imageUrl: 'https://images.pexels.com/photos/2313686/pexels-photo-2313686.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Singapore Chili Crab Noodles',
    ingredients: '300g crab meat ($8.00), 200g egg noodles ($1.50), 1/2 cup chili sauce ($0.80), 2 tbsp tomato paste ($0.30), 3 garlic cloves ($0.15), ginger ($0.30), spring onions ($0.40), egg ($0.40)',
    instructions: '1. Cook noodles. 2. Fry garlic, ginger. 3. Add chili sauce, tomato paste, 1/2 cup water. 4. Add crab, simmer 5 min. 5. Crack egg into sauce, stir gently. 6. Toss noodles in sauce, top with spring onions.',
    timeTaken: 'Prep: 10min, Cook: 15min',
    cost: 11.85,
    tags: ['singaporean', 'seafood', 'spicy', 'noodles'],
    description: 'worth every dollar',
    imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Malaysian Nasi Lemak Bowl',
    ingredients: '2 cups rice ($0.80), 1 can coconut milk ($2.00), pandan leaf ($0.50), 2 eggs ($0.80), 1/2 cup peanuts ($0.80), cucumber ($0.60), sambal ($1.00), ikan bilis ($1.50)',
    instructions: '1. Cook rice with coconut milk and pandan. 2. Hard boil eggs, slice. 3. Roast peanuts. 4. Fry ikan bilis until crispy. 5. Assemble bowl: coconut rice, egg, peanuts, ikan bilis, cucumber, sambal.',
    timeTaken: 'Prep: 10min, Cook: 25min',
    cost: 8.00,
    tags: ['malaysian', 'rice', 'coconut', 'spicy'],
    description: 'malaysian breakfast king',
    imageUrl: 'https://images.unsplash.com/photo-1666239308347-4292ea2ff777?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Taiwanese Beef Noodle Soup',
    ingredients: '300g beef shank ($4.50), 200g thick noodles ($1.50), 4 cups beef stock ($2.00), 3 tbsp soy sauce ($0.30), 2 tbsp rice wine ($0.30), star anise ($0.30), bok choy ($1.00), spring onion ($0.20)',
    instructions: '1. Braise beef in stock, soy sauce, wine, star anise for 1.5 hours until tender. 2. Cook noodles separately. 3. Blanch bok choy. 4. Assemble: noodles, beef, pour broth, top with bok choy and spring onions.',
    timeTaken: 'Prep: 15min, Cook: 90min',
    cost: 10.10,
    tags: ['taiwanese', 'beef', 'soup', 'noodles', 'meal-prep'],
    description: 'slow cook sunday vibes',
    imageUrl: 'https://images.pexels.com/photos/1907244/pexels-photo-1907244.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  
  // ITALIAN/MEDITERRANEAN
  {
    title: 'Creamy Tuscan Chicken',
    ingredients: '2 chicken breasts ($5.00), 1 cup cream ($1.50), 1 cup sun-dried tomatoes ($2.00), 2 cups spinach ($1.00), 4 garlic cloves ($0.20), parmesan ($1.50), pasta ($1.20)',
    instructions: '1. Cook pasta. 2. Pan-fry chicken until golden, slice. 3. In same pan, fry garlic. 4. Add cream, sun-dried tomatoes, simmer. 5. Add spinach and parmesan until wilted. 6. Add chicken back, toss with pasta.',
    timeTaken: 'Prep: 10min, Cook: 20min',
    cost: 12.40,
    tags: ['italian', 'chicken', 'pasta', 'creamy'],
    description: 'restaurant quality at home',
    imageUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Prosciutto & Arugula Pizza',
    ingredients: '1 pizza base ($2.50), 1/2 cup tomato sauce ($0.40), 200g mozzarella ($3.00), 100g prosciutto ($3.50), 2 cups arugula ($1.50), parmesan ($1.00), balsamic glaze ($0.60)',
    instructions: '1. Spread sauce on base, add mozzarella. 2. Bake at 220°C for 12 min. 3. Top with prosciutto and fresh arugula. 4. Shave parmesan over top. 5. Drizzle balsamic glaze.',
    timeTaken: 'Prep: 5min, Cook: 12min',
    cost: 12.50,
    tags: ['italian', 'pizza', 'prosciutto', 'quick'],
    description: 'fancy pizza night',
    imageUrl: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Seafood Linguine Marinara',
    ingredients: '200g linguine ($1.20), 200g mixed seafood ($6.00), 1 can crushed tomatoes ($1.20), 4 garlic cloves ($0.20), white wine ($1.00), chili flakes ($0.10), parsley ($0.60), olive oil ($0.50)',
    instructions: '1. Cook linguine. 2. Fry garlic and chili in olive oil. 3. Add white wine, reduce. 4. Add tomatoes, simmer 10 min. 5. Add seafood, cook 3-4 min. 6. Toss with pasta, garnish with parsley.',
    timeTaken: 'Prep: 10min, Cook: 20min',
    cost: 10.80,
    tags: ['italian', 'seafood', 'pasta', 'tomato'],
    description: 'seafood pasta done right',
    imageUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  
  // MEXICAN/LATIN
  {
    title: 'Beef Barbacoa Tacos',
    ingredients: '500g beef chuck ($6.00), 3 chipotle peppers ($0.80), 4 garlic cloves ($0.20), cumin ($0.20), oregano ($0.20), lime ($0.50), 8 corn tortillas ($1.60), onion & cilantro ($0.60)',
    instructions: '1. Blend chipotles, garlic, cumin, oregano, lime juice. 2. Coat beef, slow cook 4 hours until tender. 3. Shred beef. 4. Warm tortillas. 5. Assemble tacos with beef, diced onion, cilantro, lime.',
    timeTaken: 'Prep: 15min, Cook: 240min',
    cost: 10.10,
    tags: ['mexican', 'beef', 'tacos', 'slow-cook', 'meal-prep'],
    description: 'meal prep king',
    imageUrl: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Chicken Enchiladas Verde',
    ingredients: '400g chicken thigh ($4.80), 8 tortillas ($1.60), 2 cups green salsa ($2.50), 2 cups cheese ($2.40), 1 cup sour cream ($1.50), jalapeños ($0.80), cilantro ($0.40)',
    instructions: '1. Cook and shred chicken. 2. Mix chicken with 1 cup salsa and half the cheese. 3. Fill tortillas, roll up. 4. Place in baking dish, pour remaining salsa, top with cheese. 5. Bake 20 min at 180°C. 6. Top with sour cream, jalapeños, cilantro.',
    timeTaken: 'Prep: 20min, Cook: 30min',
    cost: 14.00,
    tags: ['mexican', 'chicken', 'baked', 'cheesy'],
    description: 'cheesy mexican heaven',
    imageUrl: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Carne Asada Fries',
    ingredients: '300g flank steak ($5.00), 4 large potatoes ($2.00), 1 cup cheese ($1.20), 1/2 cup guacamole ($1.50), 1/2 cup sour cream ($0.75), pico de gallo ($1.00), lime ($0.50)',
    instructions: '1. Marinate steak in lime, garlic, cumin. 2. Cut potatoes into fries, bake until crispy (30 min at 220°C). 3. Grill steak, slice thin. 4. Layer: fries, cheese, steak. 5. Broil until cheese melts. 6. Top with guac, sour cream, pico.',
    timeTaken: 'Prep: 15min, Cook: 35min',
    cost: 11.95,
    tags: ['mexican', 'beef', 'fries', 'loaded'],
    description: 'loaded fries game changer',
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  
  // INDIAN/MIDDLE EASTERN
  {
    title: 'Butter Chicken (Restaurant Style)',
    ingredients: '600g chicken thigh ($7.20), 2 cans crushed tomatoes ($2.40), 1 cup cream ($1.50), 100g butter ($1.50), 4 garlic cloves ($0.20), ginger ($0.40), garam masala ($0.60), kasuri methi ($0.40), rice ($0.80)',
    instructions: '1. Marinate chicken in yogurt and spices. 2. Grill or pan-fry chicken. 3. Make sauce: fry garlic, ginger, add tomatoes, simmer 15 min, blend. 4. Add cream, butter, kasuri methi. 5. Add chicken, simmer 10 min. 6. Serve with rice.',
    timeTaken: 'Prep: 20min, Cook: 35min',
    cost: 15.00,
    tags: ['indian', 'chicken', 'curry', 'creamy'],
    description: 'better than any indian restaurant',
    imageUrl: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Lamb Rogan Josh',
    ingredients: '500g lamb shoulder ($8.00), 2 onions ($1.20), 1 can crushed tomatoes ($1.20), 1 cup yogurt ($1.00), 4 garlic cloves ($0.20), ginger ($0.40), curry powder ($0.60), kashmiri chili ($0.40), rice ($0.80)',
    instructions: '1. Brown lamb pieces. 2. Fry onions until golden. 3. Add garlic, ginger, spices, fry 2 min. 4. Add tomatoes and yogurt. 5. Add lamb, simmer 1.5 hours until tender. 6. Serve with rice.',
    timeTaken: 'Prep: 15min, Cook: 90min',
    cost: 13.80,
    tags: ['indian', 'lamb', 'curry', 'slow-cook'],
    description: 'lamb curry worth the wait',
    imageUrl: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Chicken Shawarma Wrap',
    ingredients: '400g chicken thigh ($4.80), 4 pita breads ($1.60), 1 cup tahini ($1.50), 2 garlic cloves ($0.10), lemon ($0.50), lettuce ($0.80), tomato ($1.00), pickles ($0.80), sumac ($0.40)',
    instructions: '1. Marinate chicken in garlic, lemon, sumac, cumin. 2. Grill chicken, slice thin. 3. Make tahini sauce: tahini, garlic, lemon juice, water. 4. Warm pita. 5. Assemble: pita, lettuce, tomato, chicken, pickles, tahini sauce.',
    timeTaken: 'Prep: 15min, Cook: 12min',
    cost: 11.50,
    tags: ['middle-eastern', 'chicken', 'wrap', 'quick'],
    description: 'shawarma spot at home',
    imageUrl: 'https://images.unsplash.com/photo-1734772591537-15ac1b3b3c04?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Lamb Kofta with Mint Yogurt',
    ingredients: '500g lamb mince ($6.00), 1 onion ($0.60), 2 garlic cloves ($0.10), cumin ($0.20), coriander ($0.20), 1 cup Greek yogurt ($1.50), fresh mint ($0.60), pita ($1.00), salad ($1.50)',
    instructions: '1. Mix lamb, grated onion, garlic, cumin, coriander, salt. 2. Form into kofta shapes around skewers. 3. Grill or pan-fry 8-10 min. 4. Mix yogurt with chopped mint, garlic, lemon. 5. Serve with pita, salad, mint yogurt.',
    timeTaken: 'Prep: 15min, Cook: 10min',
    cost: 11.70,
    tags: ['middle-eastern', 'lamb', 'grilled', 'healthy'],
    description: 'kebab shop quality',
    imageUrl: 'https://images.unsplash.com/photo-1763647818263-62a9256f097c?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  
  // WESTERN/AUSTRALIAN
  {
    title: 'Classic Aussie Meat Pie',
    ingredients: '300g beef mince ($3.60), 1 onion ($0.60), 2 tbsp tomato sauce ($0.20), 2 tbsp worcestershire ($0.30), 1 cup beef stock ($0.50), 2 sheets puff pastry ($2.40), 1 egg ($0.40)',
    instructions: '1. Brown mince and onion. 2. Add sauces and stock, simmer 20 min until thick. 3. Cool filling. 4. Line pie tin with pastry, fill with meat. 5. Top with pastry, brush with egg. 6. Bake 30 min at 200°C until golden.',
    timeTaken: 'Prep: 15min, Cook: 50min',
    cost: 8.00,
    tags: ['australian', 'beef', 'pie', 'comfort-food'],
    description: 'aussie classic done right',
    imageUrl: 'https://images.unsplash.com/photo-1518311297794-ec7298ffba64?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Fish & Chips with Tartare',
    ingredients: '2 white fish fillets ($6.00), 4 potatoes ($2.00), 1 cup flour ($0.30), 1 cup beer ($1.50), 1/2 cup mayo ($0.60), 2 tbsp pickles ($0.40), capers ($0.50), lemon ($0.50)',
    instructions: '1. Cut potatoes into chips, fry until golden. 2. Make batter: flour, beer, salt. 3. Coat fish, deep fry 4-5 min. 4. Make tartare: mayo, chopped pickles, capers, lemon. 5. Serve fish and chips with tartare and lemon.',
    timeTaken: 'Prep: 15min, Cook: 20min',
    cost: 11.80,
    tags: ['australian', 'seafood', 'fried', 'classic'],
    description: 'beach vibes at home',
    imageUrl: 'https://images.unsplash.com/photo-1580217593608-61931cefc821?q=80&w=2231&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Gourmet Beef Burger',
    ingredients: '400g beef mince ($4.80), 4 burger buns ($2.00), 4 cheese slices ($1.20), lettuce ($0.60), tomato ($1.00), onion ($0.40), pickles ($0.60), burger sauce ($0.80), bacon ($2.00)',
    instructions: '1. Form mince into 4 patties, season well. 2. Fry bacon until crispy. 3. Cook patties 3-4 min each side, add cheese to melt. 4. Toast buns. 5. Assemble: bottom bun, sauce, lettuce, tomato, patty, cheese, bacon, onion, pickles, top bun.',
    timeTaken: 'Prep: 10min, Cook: 12min',
    cost: 13.40,
    tags: ['australian', 'beef', 'burger', 'comfort-food'],
    description: 'gourmet burger joint at home',
    imageUrl: 'https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'BBQ Ribs with Coleslaw',
    ingredients: '800g pork ribs ($9.00), 1 cup BBQ sauce ($2.00), 1/4 cabbage ($0.80), 1 carrot ($0.40), 1/2 cup mayo ($0.60), vinegar ($0.20), sugar ($0.10)',
    instructions: '1. Rub ribs with salt, pepper, paprika. 2. Bake 2 hours at 160°C wrapped in foil. 3. Unwrap, brush with BBQ sauce, bake 30 min more. 4. Make coleslaw: shred cabbage and carrot, mix with mayo, vinegar, sugar. 5. Serve ribs with coleslaw.',
    timeTaken: 'Prep: 15min, Cook: 150min',
    cost: 13.10,
    tags: ['australian', 'pork', 'bbq', 'slow-cook'],
    description: 'bbq sunday vibes',
    imageUrl: 'https://images.unsplash.com/photo-1560024818-2c6d122cfbe2?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Chicken Parmi (Parmigiana)',
    ingredients: '2 chicken breasts ($5.00), 1 cup panko ($0.60), 1 egg ($0.40), 1 cup tomato sauce ($0.80), 200g mozzarella ($3.00), parmesan ($1.00), chips & salad to serve ($2.50)',
    instructions: '1. Pound chicken flat, coat in flour, egg, panko. 2. Fry until golden. 3. Top with tomato sauce and cheeses. 4. Bake 15 min until cheese melts. 5. Serve with chips and salad.',
    timeTaken: 'Prep: 15min, Cook: 25min',
    cost: 13.30,
    tags: ['australian', 'chicken', 'italian-australian', 'pub-food'],
    description: 'pub classic at home',
    imageUrl: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  
  // BREAKFAST/BRUNCH
  {
    title: 'Smashed Avo on Sourdough',
    ingredients: '2 avocados ($5.00), 4 slices sourdough ($2.00), 2 eggs ($0.80), feta ($1.50), cherry tomatoes ($1.50), chili flakes ($0.10), lemon ($0.50)',
    instructions: '1. Toast sourdough. 2. Mash avocados with lemon juice, salt, pepper. 3. Poach or fry eggs. 4. Spread avo on toast, top with egg. 5. Crumble feta, add halved cherry tomatoes, sprinkle chili flakes.',
    timeTaken: 'Prep: 5min, Cook: 8min',
    cost: 11.40,
    tags: ['breakfast', 'brunch', 'vegetarian', 'avocado', 'healthy'],
    description: 'melbourne brunch at home',
    imageUrl: 'https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Big Breakfast Fry-Up',
    ingredients: '4 bacon rashers ($2.40), 4 sausages ($3.00), 4 eggs ($1.60), 2 tomatoes ($1.50), mushrooms ($1.50), 4 slices bread ($0.60), beans ($1.00)',
    instructions: '1. Fry bacon and sausages. 2. Fry eggs in bacon fat. 3. Grill tomatoes and mushrooms. 4. Heat beans. 5. Toast bread. 6. Assemble everything on plate.',
    timeTaken: 'Prep: 5min, Cook: 20min',
    cost: 11.60,
    tags: ['breakfast', 'english-breakfast', 'hearty'],
    description: 'full english for champions',
    imageUrl: 'https://images.unsplash.com/photo-1670275466352-3f17571fae5e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    userId: seedUser.id,
  },
  {
    title: 'Fluffy Buttermilk Pancakes',
    ingredients: '2 cups flour ($0.60), 2 tbsp sugar ($0.10), 2 tsp baking powder ($0.10), 1.5 cups buttermilk ($1.20), 2 eggs ($0.80), butter ($0.50), maple syrup ($2.00), berries ($3.00)',
    instructions: '1. Mix flour, sugar, baking powder. 2. Whisk buttermilk, eggs, melted butter. 3. Combine wet and dry gently. 4. Cook pancakes in buttered pan. 5. Stack, top with butter, syrup, and berries.',
    timeTaken: 'Prep: 10min, Cook: 15min',
    cost: 8.30,
    tags: ['breakfast', 'pancakes', 'sweet', 'american'],
    description: 'stack goals achieved',
    imageUrl: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  {
    title: 'Chorizo & Egg Breakfast Burrito',
    ingredients: '2 chorizo sausages ($2.40), 4 eggs ($1.60), 1 cup cheese ($1.20), 4 flour tortillas ($0.80), 1 avocado ($2.50), salsa ($1.00), sour cream ($0.75)',
    instructions: '1. Slice and fry chorizo. 2. Scramble eggs. 3. Warm tortillas. 4. Fill with chorizo, eggs, cheese. 5. Add sliced avocado, salsa. 6. Roll into burrito, serve with sour cream.',
    timeTaken: 'Prep: 5min, Cook: 10min',
    cost: 10.25,
    tags: ['breakfast', 'mexican', 'burrito', 'quick'],
    description: 'breakfast burrito game strong',
    imageUrl: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900',
    userId: seedUser.id,
  },
  ];

  console.log('Seeding recipes...');
  
  for (const recipe of recipes) {
    await prisma.recipe.create({ data: recipe });
  }

  console.log(`Seeded ${recipes.length} recipes`);
  console.log('Database seeded successfully!');

}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });